# Generated by Django 4.2 on 2023-07-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_banned",
            field=models.BooleanField(default=False, verbose_name="Заблокирован"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активен"),
        ),
    ]
