# Generated by Django 4.2 on 2023-04-21 10:01

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, upload_to=users.utils.user_directory_path, verbose_name="Фотография"),
        ),
    ]
