# Generated by Django 4.2 on 2023-05-02 05:51

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="userpic/default/default.jpg",
                upload_to=users.utils.user_directory_path,
                verbose_name="Фотография",
            ),
        ),
    ]
