services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432

    redis:
        image: redis:7.2.4-bookworm
        volumes:
            - redis_data:/data/
        ports:
            - 6379:6379

    celery:
        build:
            context: .
            dockerfile: ./celery/Dockerfile
        command: celery -A neuron worker -l info
        volumes:
            - ./emails:/code/emails

        depends_on:
            - db
            - redis

    flower:
        image: mher/flower
        ports:
            - "5555:5555"
        environment:
            CELERY_BROKER_URL: ${CELERY_BROKER_URL}
            FLOWER_PORT: 5555
        depends_on:
            - celery

    web:
        build:
            context: .
            dockerfile: ./project/Dockerfile
        entrypoint: ./entrypoint.sh uwsgi --ini uwsgi.ini
        volumes:
            - ./project/:/code
            - static:/code/static
            - media:/code/media
        expose:
            - 8000
        depends_on:
            - db
            - redis
            - celery

    nginx:
        build: ./nginx
        volumes:
            - static:/code/static
            - media:/code/media
        ports:
            - 8000:80
        depends_on:
            - web

volumes:
    static:
    media:
    postgres_data:
    redis_data:
