services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5432:5432

    redis:
        image: redis:7.2.4-bookworm
        ports:
            - 6379:6379

    celery:
        build:
            dockerfile: Dockerfile.celery
        command: celery -A neuron worker -l info
        volumes:
            - ./emails:/code/emails

        depends_on:
            - db
            - redis

    flower:
        image: mher/flower
        ports:
            - "5555:5555"
        environment:
            CELERY_BROKER_URL: ${CELERY_BROKER_URL}
            FLOWER_PORT: 5555
        depends_on:
            - celery

    web:
        build: .
        entrypoint: ./entrypoint.sh python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
            - celery
