services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ~/Документы/docker/postgres_data/neuron:/var/lib/postgresql/data/
        ports:
            - 5432:5432

    redis:
        image: redis:7.2.4-bookworm
        volumes:
            - ~/Документы/docker/redis_data/neuron:/data/
        ports:
            - 6379:6379

    celery:
        build:
            dockerfile: Dockerfile.celery
        command: celery -A neuron worker -l info
        # volumes:
        #     - ./project:/code
        depends_on:
            - db
            - redis
    web:
        build: .
        # command: python manage.py runserver 0.0.0.0:8000
        entrypoint: ./entrypoint.sh python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./project:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
            - celery
