# Generated by Django 4.2 on 2023-07-05 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_post_is_pinned"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(max_length=255, verbose_name="Текст комментария")),
                ("time_create", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликовать?")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Автор"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blog.post", verbose_name="Пост"),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
