# Generated by Django 4.2.9 on 2024-02-07 05:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL SLUG')),
                ('epigraph', models.CharField(blank=True, max_length=256, verbose_name='Эпиграф')),
                ('article', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='Титульное изображение')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закрепить')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-time_create'],
            },
        ),
    ]
