# Generated by Django 4.2 on 2023-05-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_draft",
            field=models.BooleanField(default=True, verbose_name="Черновик"),
        ),
    ]
