# Generated by Django 4.2 on 2023-05-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="Закрепить"),
        ),
    ]
