# Generated by Django 4.2 on 2023-04-21 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_options_post_epigraph_alter_post_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-time_create"], "verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
    ]
