# Generated by Django 4.2 on 2023-04-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_post_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=150, unique=True, verbose_name="URL SLUG"),
        ),
    ]
